# Form implementation generated from reading ui file 'importdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(400, 330)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout.addWidget(self.fileLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLineEdit = QtWidgets.QLineEdit(parent=ImportDialog)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.filePushButton = QtWidgets.QPushButton(parent=ImportDialog)
        self.filePushButton.setObjectName("filePushButton")
        self.horizontalLayout.addWidget(self.filePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.deckLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.deckLabel.setObjectName("deckLabel")
        self.verticalLayout.addWidget(self.deckLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=ImportDialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.subtitleLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.subtitleLabel.setEnabled(False)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        self.subtitleComboBox = QtWidgets.QComboBox(parent=ImportDialog)
        self.subtitleComboBox.setEnabled(False)
        self.subtitleComboBox.setObjectName("subtitleComboBox")
        self.verticalLayout.addWidget(self.subtitleComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.dictionaryLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.dictionaryLabel.setObjectName("dictionaryLabel")
        self.verticalLayout.addWidget(self.dictionaryLabel)
        self.dictionaryComboBox = QtWidgets.QComboBox(parent=ImportDialog)
        self.dictionaryComboBox.setObjectName("dictionaryComboBox")
        self.verticalLayout.addWidget(self.dictionaryComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportDialog)
        self.buttonBox.accepted.connect(ImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)
        ImportDialog.setTabOrder(self.fileLineEdit, self.filePushButton)

    def retranslateUi(self, ImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDialog.setWindowTitle(_translate("ImportDialog", "Dialog"))
        self.fileLabel.setText(_translate("ImportDialog", "File"))
        self.filePushButton.setText(_translate("ImportDialog", "Browse"))
        self.deckLabel.setText(_translate("ImportDialog", "Deck Name"))
        self.subtitleLabel.setText(_translate("ImportDialog", "Subtitle"))
        self.dictionaryLabel.setText(_translate("ImportDialog", "Dictionary"))
